# Generated by Django 4.2.30 on 2026-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username_email', models.CharField(blank=True, max_length=254)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='accounts_lo_ip_addr_8d55c6_idx'), models.Index(fields=['username_email', 'attempted_at'], name='accounts_lo_usernam_a21bee_idx')],
            },
        ),
    ]
