# Generated by Django 4.2.30 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnah', '0002_expand_sunnah_prayer_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunnahlog',
            name='prayer_type',
            field=models.CharField(choices=[('fajr', 'Fajr Sunnah'), ('dhuhr_before', 'Dhuhr Sunnah (2 Before)'), ('dhuhr_after', 'Dhuhr Sunnah (2 After)'), ('asr', 'Asr Sunnah'), ('maghrib', 'Maghrib Sunnah'), ('isha', 'Isha Sunnah'), ('witr', 'Witr'), ('dhuha', 'Dhuha'), ('tahajjud', 'Tahajjud')], max_length=20),
        ),
    ]
