# Generated by Django 4.2.30 on 2026-04-22 18:28

from django.db import migrations


def split_dhuhr_logs(apps, schema_editor):
    SunnahLog = apps.get_model('sunnah', 'SunnahLog')
    
    dhuhr_logs = SunnahLog.objects.filter(prayer_type='dhuhr')
    new_logs = []
    
    for log in dhuhr_logs:
        # Create dhuhr_before log
        SunnahLog.objects.create(
            user=log.user,
            date=log.date,
            prayer_type='dhuhr_before',
            completed=log.completed,
            created_at=log.created_at,
            updated_at=log.updated_at
        )
        # Create dhuhr_after log
        SunnahLog.objects.create(
            user=log.user,
            date=log.date,
            prayer_type='dhuhr_after',
            completed=log.completed,
            created_at=log.created_at,
            updated_at=log.updated_at
        )
        
    # Delete the old dhuhr logs
    dhuhr_logs.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sunnah', '0003_alter_sunnahlog_prayer_type'),
    ]

    operations = [
        migrations.RunPython(split_dhuhr_logs),
    ]
