# Generated by Django 4.2.29 on 2026-04-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprayerlog',
            name='asr_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='asr_status',
            field=models.CharField(default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='dhuhr_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='dhuhr_status',
            field=models.CharField(default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='fajr_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='fajr_status',
            field=models.CharField(default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='isha_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='isha_status',
            field=models.CharField(default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='maghrib_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyprayerlog',
            name='maghrib_status',
            field=models.CharField(default='on_time', max_length=20),
        ),
    ]
