# Generated by Django 4.2.29 on 2026-04-14 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_dailyprayerlog_asr_reason_dailyprayerlog_asr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_recalculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='asr_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='dhuhr_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='fajr_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='isha_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='maghrib_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed')], default='on_time', max_length=20),
        ),
    ]
