# Generated by Django 4.2.29 on 2026-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0003_add_streak_recalculation_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='protector_tokens',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='streak',
            name='tokens_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='asr_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed'), ('qada', 'Qada (Made Up)'), ('excused', 'Excused'), ('pending', 'Pending Evaluation')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='dhuhr_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed'), ('qada', 'Qada (Made Up)'), ('excused', 'Excused'), ('pending', 'Pending Evaluation')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='fajr_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed'), ('qada', 'Qada (Made Up)'), ('excused', 'Excused'), ('pending', 'Pending Evaluation')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='isha_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed'), ('qada', 'Qada (Made Up)'), ('excused', 'Excused'), ('pending', 'Pending Evaluation')], default='on_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='maghrib_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missed', 'Missed'), ('qada', 'Qada (Made Up)'), ('excused', 'Excused'), ('pending', 'Pending Evaluation')], default='on_time', max_length=20),
        ),
    ]
