# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0004_add_phase2_streak_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='asr_status',
            field=models.CharField(
                choices=[
                    ('on_time', 'On Time'),
                    ('late', 'Late'),
                    ('missed', 'Missed'),
                    ('qada', 'Qada (Made Up)'),
                    ('excused', 'Excused'),
                    ('pending', 'Pending Evaluation'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='dhuhr_status',
            field=models.CharField(
                choices=[
                    ('on_time', 'On Time'),
                    ('late', 'Late'),
                    ('missed', 'Missed'),
                    ('qada', 'Qada (Made Up)'),
                    ('excused', 'Excused'),
                    ('pending', 'Pending Evaluation'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='fajr_status',
            field=models.CharField(
                choices=[
                    ('on_time', 'On Time'),
                    ('late', 'Late'),
                    ('missed', 'Missed'),
                    ('qada', 'Qada (Made Up)'),
                    ('excused', 'Excused'),
                    ('pending', 'Pending Evaluation'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='isha_status',
            field=models.CharField(
                choices=[
                    ('on_time', 'On Time'),
                    ('late', 'Late'),
                    ('missed', 'Missed'),
                    ('qada', 'Qada (Made Up)'),
                    ('excused', 'Excused'),
                    ('pending', 'Pending Evaluation'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='dailyprayerlog',
            name='maghrib_status',
            field=models.CharField(
                choices=[
                    ('on_time', 'On Time'),
                    ('late', 'Late'),
                    ('missed', 'Missed'),
                    ('qada', 'Qada (Made Up)'),
                    ('excused', 'Excused'),
                    ('pending', 'Pending Evaluation'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
