# Generated by Django 4.2.29 on 2026-04-16 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayers', '0005_default_pending_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_offsets', models.JSONField(default=dict, help_text='Per-prayer minute offsets, e.g. {"Fajr": 1, "Isha": -5}')),
                ('calculation_method', models.CharField(default='MWL', help_text='Prayer calculation method name', max_length=20)),
                ('use_hanafi', models.BooleanField(default=False, help_text='Whether to use Hanafi madhab for Asr calculation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
