# Generated by Django 4.2.29 on 2026-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0006_add_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_token_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='weekly_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
