# Generated by Codex on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0007_sprint1_streak_economy'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='pause_notifications_until',
            field=models.DateField(
                blank=True,
                help_text='If set to today, notifications are paused until end of day.',
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='dailyprayerlog',
            index=models.Index(fields=['user', 'created_at'], name='prayerlog_user_created_idx'),
        ),
    ]

