# Generated by Codex on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0008_phase4_index_and_pause_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='intent_level',
            field=models.CharField(
                choices=[('foundation', 'Foundation'), ('strengthening', 'Strengthening'), ('growth', 'Growth')],
                default='foundation',
                max_length=20,
            ),
        ),
    ]

