# Generated by Django 4.2.30 on 2026-04-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0012_email_and_password_reset_tokens'),
    ]

    operations = [
    ]
