# Generated by Django 4.2.30 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0013_add_login_attempt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username_email', models.CharField(blank=True, max_length=254)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='prayers_log_ip_addr_fe0f68_idx'), models.Index(fields=['username_email', 'attempted_at'], name='prayers_log_usernam_ef8f24_idx')],
            },
        ),
    ]
