# Generated by Django 4.2.29 on 2026-04-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0014_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprayerlog',
            name='prayed_jumah',
            field=models.BooleanField(default=False, help_text='If True, indicates the Friday noon prayer was Jumah instead of Dhuhr.'),
        ),
    ]
