# Generated by Django 4.2.30 on 2026-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0015_dailyprayerlog_prayed_jumah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
