# Generated by Django 4.2.30 on 2026-05-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prayers.domain.constants


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayers', '0016_delete_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('privacy_level', models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE'), ('invite_only', 'INVITE_ONLY')], default=prayers.domain.constants.GroupPrivacy['PRIVATE'], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='prayers.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default=prayers.domain.constants.GroupRole['MEMBER'], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='prayers.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'group'], name='prayers_gro_user_id_a79573_idx'), models.Index(fields=['group', 'role'], name='prayers_gro_group_i_6b1765_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_membership'),
        ),
        migrations.AddIndex(
            model_name='groupinvitetoken',
            index=models.Index(fields=['token_hash'], name='prayers_gro_token_h_ae74bc_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitetoken',
            index=models.Index(fields=['group', 'is_revoked'], name='prayers_gro_group_i_12540c_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='prayers_gro_name_c4f139_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['privacy_level'], name='prayers_gro_privacy_c99b4d_idx'),
        ),
    ]
