# Generated by Django 4.2.30 on 2026-05-07 06:28

from django.db import migrations, models


def populate_status(apps, schema_editor):
    GroupMembership = apps.get_model('prayers', 'GroupMembership')
    # Set status based on is_active
    GroupMembership.objects.filter(is_active=True).update(status='active')
    GroupMembership.objects.filter(is_active=False).update(status='left')


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0017_add_group_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed'), ('banned', 'Banned')], default='active', max_length=20),
        ),
        migrations.RunPython(populate_status, migrations.RunPython.noop),
    ]
