# Generated by Django 4.2.30 on 2026-05-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0018_add_membership_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='is_active',
        ),
    ]
