# Generated by Django 4.2.30 on 2026-05-07 19:53

from django.db import migrations, models
import prayers.domain.constants


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0019_remove_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('left', 'LEFT'), ('removed', 'REMOVED'), ('banned', 'BANNED')], default=prayers.domain.constants.MembershipStatus['ACTIVE'], max_length=20),
        ),
    ]
